### ISSUE TITLE
[Feature] Add README.txt for this repository

### ISSUE THREAD

**Issue by sushidave** [minutogit/eMinuto-Desktop-Prototype#5]
### Status quo
The repo doesn't offer information about this project.
### Problem
It's hard for interested people to understand what this project is about.
### Solution
Add a README.txt file with the content.

### Suggestion for the content
eMinuto
Free and open source desktop software for eMinuto, a self-created, decentral, trust-based digital means of payment
Based on the idea of Minuto Cash (Linking to https://minuto.org/)

Concept
(Short description and mentionng the presentation at https://eminuto.org)

Screenshots
(A few screenshots from the presentation including image description

Features
(A list of features, see presentation slides 4,5,7, wallet)

Installation
(Requirements: Operating systems; Installation guides, User guides)

Help us
(List of options: Test the prototype, report bugs, create feature requests, develop, financing, starring this repo)

Donate 
(Link zu Liberapay page)

Contact
(same info as on the website eminuto.org)

Licence
(Type of licence)

**Comment by sushidave** [comment]
Suggestion for README.txt:
[README.txt](https://github.com/user-attachments/files/15891662/README.txt)

**Comment by minutogit** [comment]
Perfect. Thank you.
